### ISSUE TITLE
kvm multi-vcpu support

### ISSUE THREAD

**Issue by pogobanane** [Mic92/vmsh#106]
i think KvmRunWrapper will misbehave (or crash?) when hypervisor threads exit or spawn. 

Also: Support more than one KVM CPU are should be implemented. Note that a kvm cpu is not strictly required to stick to one thread, but it may switch threads!

**Comment by pogobanane** [comment]
at the same time one could merge inject_syscall and wrap_syscall into one struct which can produce a short lived injector or wrapper frontend struct

**Comment by Mic92** [comment]
New threads might be hard to track. Once that disappears should be possible so.

**Comment by pogobanane** [comment]
> New threads might be hard to track

the manpage reads like this is a solved problem. See man ptrace `PTRACE_O_{TRACECLONE, TRACEFORK, TRACEVFORK}` and their respective `PTRACE_EVENT_{CLONE, ...}`

**Comment by Mic92** [comment]
Right. That's probably how `strace -f` works.

**Comment by pogobanane** [comment]
d9db7b8b04066cbc81881af6fcbd67558cec25f7 fixes cashes. KvmRunWrapper is still quite incomplete as a debugger, but apparently sufficient for qemu.

**Comment by pogobanane** [comment]
#204 introduces ed39cca which fixes an issue during wrap_syscall device operation in multi-vcpu scenarios.

There still is a chance though, that vmsh startup will fail. Check out  #206 (0f73ff9) for that.

**Comment by Mic92** [comment]
Works for me now with 8 cores.
