### ISSUE TITLE
vmsh/hypervisor destruction

### ISSUE THREAD

**Issue by pogobanane** [Mic92/vmsh#74]
terminate vmsh and virtio-blk when hypervisor dies/vm is shut down.

**Comment by pogobanane** [comment]
this includes closing all transferred fds

**Comment by Mic92** [comment]
I would add a sigterm/sigint handler that thats a barrier and the main thread waits for this to trigger before stopping all threads and do the cleanup. Here is some code that does this: https://github.com/Mic92/envfs/blob/42bed8a2959aea39ced7b117614f7d5e5126db51/src/main.rs#L53

**Comment by Mic92** [comment]
This is implemented now.
